import {
  BaseEntity,
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from "typeorm";
import { SpecExtension } from "@common/enums";

@Entity()
export class OpenApiSpec extends BaseEntity {
  @PrimaryColumn()
  name: string;

  @Column()
  spec: string;

  @CreateDateColumn({ type: "timestamptz" })
  createdAt: Date;

  @UpdateDateColumn({ type: "timestamptz" })
  updatedAt: Date;

  @Column({ type: "enum", enum: SpecExtension, default: SpecExtension.JSON })
  extension: SpecExtension;

  @Column({ type: "bool", default: false })
  isAutoGenerated: boolean;
}
