import { BaseEntity, Entity, PrimaryColumn, Column } from "typeorm";
import { SpecExtension } from "../src/enums";

@Entity()
export class OpenApiSpec extends BaseEntity {
  @PrimaryColumn()
  name: string

  @Column()
  spec: string

  @Column({ type: "enum", enum: SpecExtension, default: SpecExtension.JSON})
  extension: SpecExtension

  @Column({ type: "bool", default: false })
  isAutoGenerated: boolean
}