kind: Pod
apiVersion: v1
metadata:
  name: test-app 
  labels:
    app: test-app 
spec:
  containers:
  - name: test-app 
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=Hello World! This is a Metlo Kubernetes with kind App"
  # Metlo Sidecar
  - name: metlo-sidecar
    image: metlo/suricata-daemon
    resources:
      requests:
        ephemeral-storage: "32Mi"
      limits:
        ephemeral-storage: "64Mi"
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /tmp
        name: socket-volume
    env:
      - name: METLO_ADDR
        value: http://<METLO_HOST_URL>:8081
      - name: METLO_KEY
        value: <YOUR_METLO_API_KEY>
  volumes:
    - name: socket-volume
      emptyDir: {}