import { Link, Box, Heading, VStack } from "@chakra-ui/react"

const KubernetesDocs = () => {
  return (
    <VStack>
      <Box w={"full"}>
        An API key can be generated by going to the
        <Link href={"/settings"} color={"blue"}>
          settings tab
        </Link>
        &nbsp;in the nav menu, going to the API Keys section and pressing `New`
        to generate a new API Key
      </Box>
      <Box w={"full"}>
        After you generate an API Key you can set up Metlo as either a daemonset
        or a sidecar.
      </Box>

      <Heading w={"full"} size={"sm"}>
        Daemonset
      </Heading>
      <Box w={"full"}>
        Here is an example
        <Link
          href={
            "https://github.com/metlo-labs/metlo/blob/develop/ingestors/kubernetes/metlo-daemonset.yaml"
          }
          color={"blue"}
        >
          &nbsp;metlo-daemonset.yaml&nbsp;
        </Link>
        file that contains just the daemonset for deploying metlo.
      </Box>

      <Heading w={"full"} size={"sm"}>
        Sidecar
      </Heading>
      <Box w={"full"}>
        <Link
          href={
            "https://github.com/metlo-labs/metlo/blob/develop/ingestors/kubernetes/metlo-sidecar.yaml"
          }
          color={"blue"}
        >
          &nbsp;metlo-sidecar.yaml&nbsp;
        </Link>
        contains an example for how to setup Metlo as a sidecar container.
      </Box>

      <Box w={"full"}>
        Be sure to replace {"`<"}METLO_HOST_URL{">`"} and {"`<"}
        YOUR_METLO_API_KEY{">`"} in the templates.
      </Box>
    </VStack>
  )
}
export default KubernetesDocs
