name: build

on:
  push:
    branches: [ "master", "develop" ]
    paths:
    - 'cli/**'
  pull_request:
    branches: [ "master", "develop" ]
    paths:
    - 'cli/**'

jobs:
  build-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'cli'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache-dependency-path: ./cli/yarn.lock
        node-version: '18.x'
        cache: 'yarn'
    - name: Yarn Install
      run: yarn
      working-directory: 'cli'
    - name: Yarn Build
      run: yarn build
      working-directory: 'cli'
