name: Deploy Develop Images

on:
  push:
    branches:    
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: develop
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: make build-dockers 
      - name: Push
        run: make push-dockers